# Configuración HOG para FC Detection Project

# Configuración del Extractor de Características
feature_extractor:
  type: hog
  params:
    orientations: 9
    pixels_per_cell: [8, 8]
    cells_per_block: [3, 3]
    block_norm: 'L2-Hys'
    target_size: [200, 200]
    transform_sqrt: true

# Configuración de Arquitectura del Modelo
model:
  name: 'detection_hog'
  architecture:
    - units: 512
      activation: relu
      batch_norm: true
      dropout: 0.3
    - units: 256
      activation: relu
      batch_norm: true
      dropout: 0.3
    - units: 128
      activation: relu
      batch_norm: true
      dropout: 0.2
    - units: 64
      activation: relu
      dropout: 0.2
    - units: 4
      activation: sigmoid
      batch_norm: false
      dropout: 0.0
  
  l2_reg: 0.0

# Configuración de Entrenamiento
training:
  epochs: 100
  batch_size: 32
  optimizer: 'adam'
  learning_rate: 0.001
  loss: 'mse'
  metrics: ['mae']
  
  # Callbacks
  callbacks:
    early_stopping:
      enabled: true
      monitor: 'val_loss'
      patience: 15
      mode: 'min'
    
    reduce_lr:
      enabled: true
      monitor: 'val_loss'
      factor: 0.5
      patience: 7
      min_lr: 1.0e-7
      mode: 'min'
    
    model_checkpoint:
      enabled: true
      monitor: 'val_loss'
      save_best_only: true
      mode: 'min'
    
    tensorboard:
      enabled: true

# Configuración de Datos
data:
  train_ratio: 0.8
  shuffle: true
  seed: 42

# Rutas
paths:
  images: 'data/raw/images'
  annotations: 'data/raw/annotations'
  processed: 'data/processed'
  models: 'models'
  logs: 'logs'
  results: 'results'

# Configuración de Evaluación
evaluation:
  iou_thresholds: [0.5, 0.75, 0.9]
